In [13]:
import numpy as np

# Matrix 2*2
_list1 = np.array([[542, 'Mohammad'], [784, 'Ali']])

# Access to column 2 values
print(_list1[:, 1])

# Access to row 2 and column 1
print(_list1[1, 0])


['Mohammad' 'Ali']
784


In [7]:
# Matrix 3*3
_list2 = np.array([[12, 45, 78], [49, 13, 48], [56, 89, 19]])

# Access to row 2 and column 3
print(_list2[1, 2])

# Access to row 3 and column 1
print(_list2[2, 0])

# Access to row 1 and column 1
print(_list2[0, 0])

48
56
12


In [19]:
# Matrix 4*3
_list3 = np.array([[1982, 345, 7008], [439, 193, 418], [5156, 809, 199], [456, 972, 9721]])

# Access to row 3 and column 2
print(_list3[2, 1])

# Access to row 3
print(_list3[2, :])

# Access to column 3
print(_list3[:, 2])

# Access to row 1&2 and column 2&3
print(_list3[0:2, 1:3])

809
[5156  809  199]
[7008  418  199 9721]
[[ 345 7008]
 [ 193  418]]
